apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: product
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo Success!! > /output/success.txt']
    volumeMounts:
    - name: my-vol
      path: /output/
  volumes:
  - name: my-vol
    persistentVolumeClaim:
      name: pvc-1