apiVersion: v1
kind: Pod
metadata: 
  name: hostpath-pod
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['sh', '-c', 'echo Hello-world!!! > /input/welcome.txt']
    volumeMounts:
    - name: my-vol
      mountPath: /input
  volumes:
  - name: my-vol
    hostPath:
      path: /var/my-data