apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ['sh', '-c', 'while true; do echo Harsha!! >> /output/output.txt; sleep 5; done']
        volumeMounts:
        - name: my-vol
          mountPath: /output
      volumes:
      - name: my-vol
        persistentVolumeClaim:
          claimName: pvc