apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-vol1
spec:
  capacity: 
    storage: 1Gi
  accessModes: 
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 34.48.122.59
    path: /opt/sfw