apiVersion: v1 
kind: Pod 
metadata:
  name: test-pod
  labels:
    app: product
spec:
  containers:
  - image: radial/busyboxplus:curl
    name: busybox 
    command: ['sh', '-c', 'while true; do sleep 10; done']