apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nodeport-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - image: evopswithcloudhub/python_webpage:red
        name: webapp-cont