apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
        app: currency
    spec:
      containers:
      - image: devopswithcloudhub/python_webpage:greencont
        name: greencont