apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 2
  selector:
    app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
      - image: nginx
        name: nginx