apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment
      dc: hyd
  template:
    metadata:
      labels:
        app: payment
        dc: hyd
    spec:
      containers:
      - name: nginx
        image: nginx