apiVersion: v1
kind: Pod
metadata:
  name: cm-secret-pod
spec:
  containers: 
  - image: busybox
    name: busybox
    command: ['sh', '-c', 'while true; do echo configmap is $CONFIGMAPVAR & secret is $SECRETVAR; sleep 10; done']
    env: 
    - name: CONFIGMAPVAR
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: intro
    - name: SECRETVAR
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: secret2