apiVersion: v1
kind: Pod
metadata:
  name: new-pod
spec: 
  containers:
  - image: busybox
    name: busybox
    command: ['sh', '-c', 'echo username is $(cat /config/name) && sleep 300']
    volumeMounts:
    - name: my-cm-vol
      mountPath: /config/
  volumes:
  - name: my-cm-vol
    configMap:
      name: my-config