apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['sh', '-c', 'echo secret is $SECRETVAR && sleep 3600']
    env:
    - name: SECRETVAR
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: secret2