apiVersion: v1
kind: Pod
metadata:
  name: secret-vol
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['sh', '-c', 'echo username $(cat /my-conf/course) && sleep 600']
    volumeMounts:
    - name: my-secret-vol
      mountPath: /my-conf/
  volumes:
  - name: my-secret-vol
    secret:
      secretName: my-secret