apiVersion: v1
kind: Pod
metadata:
  name: bigpod
spec: 
  containers: 
  - image: busybox
    name: busybox
    command: 
      - 'sh'
      - '-c'
      - 'echo K8S!! && sleep 300'
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      requests:
        cpu: 4000m
        memory: 5000Mi