apiVersion: v1
kind: Pod
metadata:
  name: burstable
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      requests:
        cpu: 128m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 500Mi