apiVersion: v1
kind: Pod
metadata:
  name: guaranteed
spec:
  containers:
  - image: nginx
    name: nginx
    ports: 
    - containerPort: 80
      protocol: TCP
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits: 
        cpu: 100m
        memory: 256Mi