apiVersion: v1
kind: Pod
metadata:
  name: regular-pod
spec:
  containers:
  - image: busybox
    name: busybox
    command:
      - 'sh'
      - '-c'
      - 'echo k8s!!! && sleep 3600'
    resources:
      requests:
        cpu: 250m
        memory: 250Mi