apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-pods
  namespace: boutique
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: harsha
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io