apiVersion: v1
kind: Pod
metadata:
  name: exec-pod
spec:
  containers:
  - image: busybox
    name: busybox
    command: 
    - 'sh'
    - '-c'
    - 'echo liveness probe && sleep 300'
    livenessProbe:
      initialDelaySeconds: 5
      exec:
        command: ['echo', 'Hello World!!']