apiVersion: v1
kind: Pod
metadata:
  name: ready-pod
spec:
  containers:
  - image: nginx
    name: nginx
    readinessProbe:
      initialDelaySeconds: 10
      httpGet:
        path: /health
        port: 80