apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeselector
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: catalog
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels: 
        app: catalog
    spec: 
      containers:
      - image: nginx
        name: nginx
      nodeSelector:
        disktype: magnetic