apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefer-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - image: nginx
        name: nginx
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: env
                operator: In
                values:
                - dev
                - test