apiVersion: v1
kind: Pod
metadata: 
  name: green-pod
spec:
  containers: 
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
  tolerations:
  - key: "color"
    operator: "Equal"
    value: "green"
    effect: "NoSchedule"